### ISSUE TITLE
Try to apply PGO

### ISSUE THREAD

**Issue by zamazan4ik** [ajeetdsouza/loxcraft#18]
Did you try applying [PGO](https://doc.rust-lang.org/rustc/profile-guided-optimization.html) to optimize the compiler further based on runtime information? This technique is already used by e.g. `rustc` and `cpython`. More about PGO results (with actual numbers) in other applications you can find here - https://github.com/zamazan4ik/awesome-pgo .

**Comment by ajeetdsouza** [comment]
We've tried running PGO on the benchmarks themselves, but unfortunately, there was no measurable difference in performance.
